platform :ios, '9.0'

use_frameworks!
target "Skroman" do

pod 'Alamofire', '~> 4.4'
pod 'AlamofireJsonToObjects'
pod 'SVProgressHUD'
pod 'ReachabilitySwift'
pod 'TWMessageBarManager'
pod 'TPKeyboardAvoiding'
pod 'Masonry'
pod 'SDWebImage', '3.7.3'
pod 'KMPlaceholderTextView', '~> 1.3.0'
#pod 'FacebookCore'
#pod 'FacebookLogin'
#pod 'FacebookShare'
#pod 'Google/SignIn'
#pod 'TwitterKit'
pod 'RNLoadingButton-Swift'
pod 'ActionSheetPicker-3.0', '~> 2.2.0'
pod 'SwiftLocation'
pod 'GooglePlaces'
pod 'AlamofireNetworkActivityLogger', '~> 2.0'
pod 'MWPhotoBrowser'
pod 'PEPhotoCropEditor'
pod 'GoogleSignIn'
pod 'SideMenu'
#pod 'CocoaMQTT'
pod 'MQTTClient'
pod 'FMDB'
pod 'SwipeCellKit'
pod 'PageMenu'
pod 'STPopup'
pod 'Firebase/Auth'
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git',:branch => 'clamping-function'
pod 'p2.OAuth2'
pod 'Firebase/Core'
pod 'Fabric'
pod 'Crashlytics'
end

